# .github/workflows/run-scala-scripts.yml
name: Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Scala CLI
      run: |
        curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.8.0/sbt-1.8.0.zip
        unzip sbt.zip -d ~/sbt
        export PATH=~/sbt/sbt/bin:$PATH
        sbt sbtVersion

    - name: Compile and test
      run: |
        sbt clean compile test